DROP TABLE IF EXISTS chat CASCADE;
CREATE TABLE chat (
  id SERIAL PRIMARY KEY NOT NULL,
  messages VARCHAR(255) NOT NULL,
  username VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT now()
);