DROP TABLE IF EXISTS chat CASCADE;
CREATE TABLE chat (
  id SERIAL PRIMARY KEY NOT NULL,
  messages VARCHAR(255) NOT NULL,
  sender INTEGER REFERENCES users(id) ON DELETE CASCADE,
  main_party_id INTEGER REFERENCES main_parties(id) ON DELETE CASCADE
);